Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [ ]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('/content/movies.csv', engine='python', sep=',',error_bad_lines=False)

<ipython-input-18-fbaf14ac6de5>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  movies_data = pd.read_csv('/content/movies.csv', engine='python', sep=',',error_bad_lines=False)
Skipping line 535: unexpected end of data


In [ ]:
# printing the first 5 rows of the dataframe
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
# number of rows and columns in the data frame

movies_data.shape

(533, 24)

In [ ]:
# selecting the relevant features for recommendation

selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [ ]:
# replacing the null valuess with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [ ]:
# combining all the 5 selected features

combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [ ]:
print(combined_features)

0      Action Adventure Fantasy Science Fiction cultu...
1      Adventure Fantasy Action ocean drug abuse exot...
2      Action Adventure Crime spy based on novel secr...
3      Action Crime Drama Thriller dc comics crime fi...
4      Action Adventure Science Fiction based on nove...
                             ...                        
528    Drama Action History Thriller paris assassinat...
529    Action Drama War u.s. army nigeria president H...
530    Action Comedy Thriller Romance assassin Perfec...
531    Comedy Action Adventure spy cold war remake ba...
532    Comedy upper class mother single parent parent...
Length: 533, dtype: object


In [ ]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (0, 581)	0.17256233688205283
  (0, 1917)	0.11971602235051768
  (0, 3189)	0.21913935447462854
  (0, 2489)	0.16999722099834375
  (0, 2139)	0.24491017404312235
  (0, 3576)	0.18898942835378885
  (0, 4076)	0.2298352109827025
  (0, 3438)	0.24491017404312235
  (0, 3262)	0.21084300362725736
  (0, 4235)	0.21084300362725736
  (0, 4182)	0.21084300362725736
  (0, 3268)	0.15410509463516792
  (0, 2809)	0.2298352109827025
  (0, 2719)	0.10550573625247181
  (0, 4178)	0.1230677890743829
  (0, 3739)	0.07065945722866872
  (0, 1204)	0.24491017404312235
  (0, 3491)	0.19833315645054664
  (0, 764)	0.2298352109827025
  (0, 4044)	0.13543760055412712
  (0, 3520)	0.3050455045544421
  (0, 1440)	0.15252275227722106
  (0, 723)	0.2298352109827025
  (0, 890)	0.24491017404312235
  (0, 1314)	0.08564885193465269
  :	:
  (532, 2849)	0.230973596695095
  (532, 3950)	0.230973596695095
  (532, 2822)	0.21675647218520105
  (532, 3279)	0.1603235541992831
  (532, 2572)	0.19245213730498784
  (532, 32)	0.14852557803189811
  (532,

Cosine Similarity

In [ ]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.06268373 0.03401232 ... 0.00377538 0.05293751 0.01351637]
 [0.06268373 1.         0.02676861 ... 0.00332867 0.05199805 0.        ]
 [0.03401232 0.02676861 1.         ... 0.00412587 0.06150149 0.04291854]
 ...
 [0.00377538 0.00332867 0.00412587 ... 1.         0.01031423 0.05030615]
 [0.05293751 0.05199805 0.06150149 ... 0.01031423 1.         0.00620234]
 [0.01351637 0.         0.04291854 ... 0.05030615 0.00620234 1.        ]]


In [ ]:
print(similarity.shape)

(533, 533)


Getting the movie name from the user

In [ ]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : Iron Man


In [ ]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [ ]:
close_match = find_close_match[0]
print(close_match)

Iron Man


In [ ]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

68


In [ ]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.02131431309481384), (1, 0.047357119555582354), (2, 0.0077917373797518445), (3, 0.003997677353250025), (4, 0.02020867747128917), (5, 0.007266820654880759), (6, 0.0902048763513027), (7, 0.2012395488119193), (8, 0.003951034059364093), (9, 0.05297995879236586), (10, 0.05351719406517292), (11, 0.006171478423257472), (12, 0.0077720790213511555), (13, 0.006615208130106753), (14, 0.06738298347054401), (15, 0.003597767265717091), (16, 0.1942942597949193), (17, 0.006947857587526831), (18, 0.03753430628411817), (19, 0.07487405103137468), (20, 0.04915422626180023), (21, 0.006171762010668022), (22, 0.0034677725481880224), (23, 0.0032280682827609294), (24, 0.006123499507384207), (25, 0.0), (26, 0.1740089851436909), (27, 0.02030288213786096), (28, 0.05278730424400868), (29, 0.0074702190396113075), (30, 0.04882336572150632), (31, 0.2818288248565288), (32, 0.03259472211815671), (33, 0.09059045269144063), (34, 0.0), (35, 0.023883670962777), (36, 0.021764045813923213), (37, 0.0038281062844983606),

In [ ]:
len(similarity_score)

533

In [ ]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(68, 1.0000000000000002), (79, 0.36107950559280405), (31, 0.2818288248565288), (7, 0.2012395488119193), (16, 0.1942942597949193), (26, 0.1740089851436909), (85, 0.15918952671582695), (182, 0.1379128449885697), (511, 0.12207885893729994), (353, 0.12028281039277254), (131, 0.11399660939205404), (138, 0.10797835075936249), (46, 0.10700057241116258), (64, 0.10375127975598086), (203, 0.10285056862977195), (307, 0.09952478156363517), (174, 0.09663328879617583), (169, 0.09608617647117267), (101, 0.09492181284636886), (94, 0.09415118571177704), (126, 0.09411971619219887), (33, 0.09059045269144063), (6, 0.0902048763513027), (205, 0.08735030770351085), (356, 0.08566104702396266), (198, 0.08500755334258234), (361, 0.08365844326679675), (39, 0.08255746174958993), (318, 0.08235414146761953), (396, 0.08072266406834994), (78, 0.07871548078919487), (436, 0.07710048606192528), (501, 0.0750080664854223), (19, 0.07487405103137468), (421, 0.07197709399163572), (91, 0.07121374612401184), (38, 0.0707593905

In [ ]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . The Avengers
6 . Captain America: Civil War
7 . Captain America: The Winter Soldier
8 . Ant-Man
9 . X-Men
10 . Tropic Thunder
11 . G-Force
12 . The Last Airbender
13 . X-Men: Days of Future Past
14 . X-Men: Apocalypse
15 . X2
16 . The Expendables 3
17 . The Incredible Hulk
18 . Captain America: The First Avenger
19 . X-Men: First Class
20 . Guardians of the Galaxy
21 . Thor: The Dark World
22 . X-Men: The Last Stand
23 . Tangled
24 . Sherlock Holmes: A Game of Shadows
25 . Sherlock Holmes
26 . R.I.P.D.
27 . You Don't Mess with the Zohan
28 . TRON: Legacy
29 . Surf's Up


Movie Recommendation Sytem

In [ ]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : Avengers
Movies suggested for you : 

1 . The Avengers
2 . Avengers: Age of Ultron
3 . Captain America: The Winter Soldier
4 . Captain America: Civil War
5 . Iron Man 2
6 . Thor: The Dark World
7 . X-Men
8 . The Incredible Hulk
9 . Thor
10 . Captain America: The First Avenger
11 . Ant-Man
12 . X-Men: Apocalypse
13 . X-Men: The Last Stand
14 . X2
15 . Iron Man
16 . X-Men: Days of Future Past
17 . Iron Man 3
18 . The Amazing Spider-Man 2
19 . Man of Steel
20 . Zodiac
21 . Batman v Superman: Dawn of Justice
22 . Teenage Mutant Ninja Turtles: Out of the Shadows
23 . X-Men: First Class
24 . The Jungle Book
25 . Guardians of the Galaxy
26 . Sherlock Holmes
27 . The Island
28 . Watchmen
29 . Fantastic Four
